- hosts: 192.168.56.104
  connection: local
  
  tasks:
  - name: Create & Start Container
    docker_container:
      name: myweb
      image: "skwhjj/tomcat:latest"
      state: started
      ports:
      - "80:8080"

